---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dbz-kafkaconnect-cm
  labels:
    app: dbz-kafkaconnect
data:
  BOOTSTRAP_SERVERS: "pkc-z9doz.eu-west-1.aws.confluent.cloud:9092"
  CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "3"
  CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "3"
  CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "3"
  CONNECT_PLUGIN_PATH: "/kafka/connect,/kafka/connect/debezium-connector-postgres"
  PLUGIN_PATH: "/kafka/connect/,/kafka/connect/debezium-connector-postgres"
  KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  CONNECT_REST_ADVERTISED_HOST_NAME: "connect"
  CONNECT_REST_PORT: "8083"
  CONNECT_GROUP_ID: "connect"
  CONFIG_STORAGE_TOPIC: "dbz-connect-configs"
  OFFSET_STORAGE_TOPIC: "dbz-connect-offsets"
  STATUS_STORAGE_TOPIC: "dbz-connect-status"
  CONNECT_SECURITY_PROTOCOL: "SASL_SSL"
  CONNECT_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username='RKXXIYTO7OZGIXL2' password='7dax40ptS0MhprbtFBUn6/jIQXWgZw5jw8xzSdvIRvZAPMXgAKKids/XFrJW0ala';"
  CONNECT_SASL_MECHANISM: "PLAIN"
  # Connect producer
  CONNECT_PRODUCER_SECURITY_PROTOCOL: "SASL_SSL"
  CONNECT_PRODUCER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username='RKXXIYTO7OZGIXL2' password='7dax40ptS0MhprbtFBUn6/jIQXWgZw5jw8xzSdvIRvZAPMXgAKKids/XFrJW0ala';"
  CONNECT_PRODUCER_SASL_MECHANISM: "PLAIN"
  # Connect consumer
  CONNECT_CONSUMER_SECURITY_PROTOCOL: "SASL_SSL"
  CONNECT_CONSUMER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username='RKXXIYTO7OZGIXL2' password='7dax40ptS0MhprbtFBUn6/jIQXWgZw5jw8xzSdvIRvZAPMXgAKKids/XFrJW0ala';"
  CONNECT_CONSUMER_SASL_MECHANISM: "PLAIN"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbz-kafkaconnect-dp
  labels:
    app: dbz-kafkaconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbz-kafkaconnect
  template:
    metadata:
      labels:
        app: dbz-kafkaconnect
    spec:
      containers:
        - name: dbz-kafkaconnect
          image: public.ecr.aws/k9a0b2l8/debezium-strimzi-postgresql:2.3.2.Final
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: dbz-kafkaconnect-cm
          ports:
            - containerPort: 8083
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dbz-kafkaconnect-srv
  labels:
    app: dbz-kafkaconnect
spec:
  ports:
    - name: tcp8083
      protocol: TCP
      port: 8083
    - name: tcp8080
      protocol: TCP
      port: 8080
  selector:
    app: dbz-kafkaconnect
