version: "3.9"
services:
  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION}
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - "./sql/mysql-inventory.sql:/docker-entrypoint-initdb.d/1.sql"
  postgresql:
    image: postgres:14
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - "./sql/pg_hba.conf:/etc/postgresql/pg_hba.conf"
      - "./sql/postgresql.conf:/etc/postgresql/postgresql.conf"
      - "./sql/postgresql-inventory.sql:/docker-entrypoint-initdb.d/1.sql"
  db-adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9081:9081
    depends_on:
      - kafka
    environment:
      - SERVER_PORT=9081
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - KAFKA_CLUSTERS_0_NAME=local
  connect:
    build:
      context: ./docker/connect-smt
    ports:
      - 8083:8083
      - 8778:8778
    depends_on:
      - kafka
      - mysql
      - postgresql
      - schema-registry
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - ENABLE_JOLOKIA=true
  debezium-ui:
    image: debezium/debezium-ui:latest
    ports:
      - 9080:8080
    depends_on:
      - connect
    environment:
      - KAFKA_CONNECT_URI=http://connect:8083
      - ENABLE_DEBEZIUM_SCRIPTING=true
  schema-registry:
    image: confluentinc/cp-schema-registry
    ports:
      - 8181:8181
      - 8081:8081
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8081
      - SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS=GET,POST,PUT,OPTIONS
      - SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN='*'
    depends_on:
      - zookeeper
  schema-registry-ui:
    image: landoop/schema-registry-ui
    ports:
      - 8000:8000
    depends_on:
      - schema-registry
    environment:
      - SCHEMAREGISTRY_URL=http://schema-registry:8081
      - PROXY=true
  prometheus:
    build:
      context: ./docker/debezium-prometheus
      args:
        PROMETHEUS_VERSION: v2.26.0
    ports:
      - 9090:9090
    depends_on:
      - connect
  grafana:
    build:
      context: ./docker/debezium-grafana
      args:
        GRAFANA_VERSION: 7.5.5
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    environment:
      - DS_PROMETHEUS=prometheus
