version: "3.9"
services:
  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION}
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - "${PWD}/../sql/mysql-inventory.sql:/docker-entrypoint-initdb.d/1.sql"
#  db2:
#    image: db2server:openexpo
#    ports:
#      - 50000:50000
#    privileged: true
#    environment:
#      - LICENSE=accept
#      - DBNAME=TESTDB
#      - DB2INST1_PASSWORD=Password!
  postgresql:
    image: postgres:11
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - "${PWD}/../sql/pg_hba.conf:/etc/postgresql/pg_hba.conf"
      - "${PWD}/../sql/postgresql.conf:/etc/postgresql/postgresql.conf"
      - "${PWD}/../sql/postgresql-inventory.sql:/docker-entrypoint-initdb.d/1.sql"
  db-adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
#  kafkdrop:
#    image: obsidiandynamics/kafdrop
#    ports:
#      - 8081:8081
#    depends_on:
#      - zookeeper
#      - kafka
#    environment:
#      - KAFKA_BROKERCONNECT=kafka:9092
#      - SERVER_SERVLET_CONTEXTPATH=/
#      - SERVER_PORT=8081
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9081:9081
    depends_on:
      - kafka
    environment:
      - SERVER_PORT=9081
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - KAFKA_CLUSTERS_0_NAME=local
  connect:
    image: debezium/connect
    ports:
      - 8083:8083
    depends_on:
      - kafka
      - mysql
      - postgresql
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
  debezium-ui:
    image: debezium/debezium-ui:latest
    ports:
      - 9080:8080
    depends_on:
      - connect
    environment:
      - KAFKA_CONNECT_URI=http://connect:8083