---
kind: ConfigMap
apiVersion: v1
metadata:
  name: postgres-cm
  labels:
    app: postgres
data:
  POSTGRES_PASSWORD: "pgpass"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "postgres"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-dp
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: debezium/postgres:15
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: postgres-cm
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres-cm
spec:
  ports:
    - name: tcp5432
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: adminer
  labels:
    app: adminer
spec:
  type: LoadBalancer
  selector:
    app: adminer
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  labels:
    app: adminer
spec:
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer
          ports:
            - containerPort: 8080
